# Generated by Django 5.1.7 on 2025-06-08 15:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0001_initial'),
        ('reservation_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='match',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='match',
            name='cible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_recus', to='reservation_app.user'),
        ),
        migrations.AlterField(
            model_name='match',
            name='liked',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='match',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_faits', to='reservation_app.user'),
        ),
    ]
